Feature/fp2
mxrstv/study pull request #3
Opened 2021-04-19 17:44 UTC by mxrstv

2021-04-19 19:53 UTC, Andrew8xx8 requested changes

2021-04-19 19:53 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        yield el
Либо `&block` либо `yield` это разные варианты одного и того же, используй что-то одно

2021-04-19 19:53 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +      def my_reduce(init_acc = nil, &block)
Тут тоже, что и выше

2021-04-23 13:55 UTC, nut4k1 approved these changes

2021-04-23 18:18 UTC, merged